// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by Carlos Padoa hibernate/HibernateEntity.vsl in andromda-vuejs-cartridge on 08/15/2022 13:36:31-0300.
//
<template>
  <div>
    <h1>NamedEntity</h1>
    <table>
    <tr>
            <th>name</th>
            <th>id</th>
          </tr>
    <tr v-for="entity in entities">
            <td>name</td>
            <td>id</td>
          </tr>
  </table>
  </div>
</template>

<script>
export default{
  data() {
    return {
      entities: [{      name: 'name',
            id: 'id',
      }]
    }
  }
}
</script>