// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by Carlos Padoa hibernate/HibernateEntity.vsl in andromda-vuejs-cartridge on 08/12/2022 10:27:24-0300.
//
<template>
  <div class="about">
    <h1>Owner</h1>
  </div>
</template>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>