// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by Carlos Padoa hibernate/HibernateEntity.vsl in andromda-vuejs-cartridge on 08/16/2022 12:07:50-0300.
//
<template>
  <div>
    <h1>Vet</h1>
    <table>
    <tr>
            <th>firstName</th>
            <th>lastName</th>
            <th>id</th>
          </tr>
    <tr v-for="entity in entities">
            <td>firstName</td>
            <td>lastName</td>
            <td>id</td>
          </tr>
  </table>
  </div>
</template>

<script>
export default{
  data() {
    return {
      entities: [{      firstName: 'firstName',
            lastName: 'lastName',
            id: 'id',
      }]
    }
  }
}
</script>